### ISSUE TITLE
Pypi installation is broken for 0.1.7

### ISSUE THREAD

**Issue by blorenz** [sibblegp/b2blaze#13]
Missing models:

```>>> from b2blaze import B2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/b2blaze/__init__.py", line 1, in <module>
    from b2blaze.b2lib import B2
  File "/usr/local/lib/python3.7/site-packages/b2blaze/b2lib.py", line 9, in <module>
    from b2blaze.models.bucket_list import B2Buckets
ModuleNotFoundError: No module named 'b2blaze.models'
```

Listing the directory:
```
Successfully installed b2blaze-0.1.7
baf197a81c1e# ls /usr/local/lib/python3.7/site-packages/b2blaze
__init__.py  b2_exceptions.py  connector.py
__pycache__  b2lib.py          utilities.py
```

**Comment by sibblegp** [comment]
Thank you very much for pointing this out!  Fixed in 0.1.8. I will add some checks in our CI system to check for this going forward.
